### PR TITLE
Feature/actor information

### PR DESCRIPTION
**Pull request by Maxiboy441**

### CODE REVIEW

**Comment by mehrb98** [comment]
Screenshot 2024-07-21 at 18 57 10

Add bottom and split card from footer (adjustment)

**Comment by mehrb98** [comment]
Screenshot 2024-07-21 at 19 02 42

ich kann nicht auf das klicken. Bug fixen bitte
Screenshot 2024-07-21 at 19 02 58

**Comment by mehrb98** [comment]
Screenshot 2024-07-21 at 19 10 40

Styles bitte in css file schieben

**Comment by Maxiboy441** [comment]
> Screenshot 2024-07-21 at 18 57 10
> Add bottom and split card from footer (adjustment)

This is only the case in a zoomed in view and people with many occupations, cause the card backgound is the same as the footer. If you scroll this sould be more clear. So dont know what to fix because this is a expected behavior

**Comment by Maxiboy441** [comment]
One requested change was to give a error each time some values are missing from the api or wikipedia, which is a loot of the time and this would make the plattform bad to use.....

**Pull request merged**
